### ISSUE TITLE
Create an about us page

### ISSUE THREAD

**Issue by Mayank77maruti** [Mayank77maruti/603WorkVed#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mumtazmumtazfb** [comment]
I would like to complete this task. Can you please assign it to me?

**Comment by Mayank77maruti** [comment]
Welcome to our repo , do star ⭐ the repo.
Happy contributing.

**Comment by mumtazmumtazfb** [comment]
Can I please get access to the design?

**Comment by Nkca122** [comment]
Can I be assigned this issue as the last responder has been removed ?
