### ISSUE TITLE
Set a favicon of webpage

### ISSUE THREAD

**Issue by Mayank77maruti** [Mayank77maruti/603WorkVed#12]
**Describe the bug**
Set a favicon of webpage

**To Reproduce**

**Video Explanation**
A clear video showing the bug.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mrhat05** [comment]
@Mayank77maruti if the work is open,i can work on it

**Comment by Mayank77maruti** [comment]
Hey @mrhat05 , Welcome to 603Workved.
Dont forget to star our repo.

**Comment by Mayank77maruti** [comment]
start working on it
