### ISSUE TITLE
Create a Blogs page 

### ISSUE THREAD

**Issue by Mayank77maruti** [Mayank77maruti/603WorkVed#13]
**Is your feature request related to a problem? Please describe.**
it will have cards and the user can click on card and read further on the topic.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Arnavpk** [comment]
We can make a good footer to add contact details. Can you assign me to this issue

**Comment by Mayank77maruti** [comment]
Hey @Arnavpk , create a new issue regarding the above , i would assign you that.

**Comment by Arnavpk** [comment]
Sure!

**Comment by Mayank77maruti** [comment]
Hey @subhamagarrwal , assigned
Do star the repo

**Comment by subhamagarrwal** [comment]
for the cards, do you want like a layout to appear once each card is clicked onto, so it will not redirect to any page but will be part of the blog page content itself @Mayank77maruti

**Comment by Mayank77maruti** [comment]
Yes as you click on card it will redirect to another page to

**Comment by subhamagarrwal** [comment]
hey ill make a PR soon, for blogs ill just make do with 3 predefined blog pages for 3 blog boxes, anyone can click on, it should work
)

**Comment by subhamagarrwal** [comment]
@Mayank77maruti 

added four pages
blogs.html
which contains three divs
on clicking each will redirect to one of the other three blogpages.html files i created.

ensured it is responsive

**Comment by subhamagarrwal** [comment]
@Mayank77maruti kindly accept it as hacktober fest pr
