### ISSUE TITLE
Make the readme file better and more impressive looking.

### ISSUE THREAD

**Issue by Mayank77maruti** [Mayank77maruti/603WorkVed#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Monika-1082005** [comment]
Can you assign this to me for hacktoberfest?

**Comment by Mayank77maruti** [comment]
Hey @Monika-1082005 , welcome to our repo.
the readme should consist of contributers list and tags like views and all that you can get from shield.io and many more changes , make it look very better. Its all on you.
Happy contributing.

**Comment by Mayank77maruti** [comment]
Don't forget to star the repo.

**Comment by Monika-1082005** [comment]
> Hey @Monika-1082005 , welcome to our repo. the readme should consist of contributers list and tags like views and all that you can get from shield.io and many more changes , make it look very better. Its all on you. Happy contributing.

Sure...Thank you!

**Comment by Mayank77maruti** [comment]
Great work.
Thank you for contributing
