### ISSUE TITLE
Change Content of our Story

### ISSUE THREAD

**Issue by Deekshashakyawal** [Mayank77maruti/603WorkVed#2]
**Describe the bug**
The our story content is not appropriate.

**To Reproduce**
1. Go to 'Home'
2. Scroll down to 'our story'
3. See error.

**Expected behavior**
A clear and concise description of story that originally belongs to the founder and team.

**Screenshots**
![Screenshot 2024-10-01 125746](https://github.com/user-attachments/assets/ac409f61-7f56-4d2b-9c74-de405988f3ad)

**Comment by Mayank77maruti** [comment]
@Deekshashakyawal Make the texts present in all the front page better

**Comment by Mayank77maruti** [comment]
#3 is merged.
