### ISSUE TITLE
Create design of about us page by canva/figma

### ISSUE THREAD

**Issue by Mayank77maruti** [Mayank77maruti/603WorkVed#23]
Take care of the theme of website

**Comment by SkullShoT007** [comment]
Hey, I would like to work on about us design, Can you Assign me this task

**Comment by Mayank77maruti** [comment]
Don't forget to star the repo.
Thank you for contributing.

**Comment by SkullShoT007** [comment]
Sure Mayank

**Comment by SkullShoT007** [comment]
Hello, I am almost going to finish the design for About us Page but dont know how to contribute it

**Comment by Mayank77maruti** [comment]
Hi @SkullShoT007 , first share the canva or figma link here, We can discuss the changes , then i would guide you to contribute it.

**Comment by SkullShoT007** [comment]
https://www.figma.com/design/nmHY7JEE6tPSWQr8sm2d7t/603?node-id=0-1&t=xW6wQvlWy87D6wr7-1 (Do tell me what do you think)

**Comment by Mayank77maruti** [comment]
I have requested for access.

**Comment by Mayank77maruti** [comment]
check your mail

**Comment by SkullShoT007** [comment]
Approved

**Comment by Mayank77maruti** [comment]
give me the access to edit .

**Comment by Mayank77maruti** [comment]
looks good 
to contribute make a .md file named ''design'' file and put it in the assests folder and put your link in there and make a pr.

**Comment by SkullShoT007** [comment]
Okay, Thanks for the info, and I have you access to edit the file
