### ISSUE TITLE
Create design of spaces page consisting of images of various offices by canva/figma

### ISSUE THREAD

**Issue by Mayank77maruti** [Mayank77maruti/603WorkVed#24]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vivekmeena9999** [comment]
Hey, I would like to work on this issue please assign this one to me.

**Comment by Mayank77maruti** [comment]
Hey @vivekmeena9999 , task assigned.
You can start working on this.

**Comment by Mayank77maruti** [comment]
Don't forget to star the repo.
Happy contributing.

**Comment by vivekmeena9999** [comment]
Hey, there sorry for the late reply. I have made the design please check it out here, if any changes need to be made them please do tell me.

File link:- [](https://www.figma.com/design/zkhIDT2PnU11QhMsV4arct?node-id=0-1)

**Comment by Mayank77maruti** [comment]
good design , keep it up.
To make a pull request in asset folder their is design.md file add your link there and make the pull request.
