### ISSUE TITLE
Integrating chatbot

### ISSUE THREAD

**Issue by Mayank77maruti** [Mayank77maruti/603WorkVed#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mayank77maruti** [comment]
you can use botpress for chatbot

**Comment by Monika-1082005** [comment]
I would like to work on this issue. May I know what all kind of queries does the chatbot needs to answer to , so it would be better to create it accordingly.

**Comment by Mayank77maruti** [comment]
Hi @Monika-1082005 , Welcome to our repo.
Our website is aimed for coworking space where companies can rent or book offices spaces so you can give information about availaibles offices location . you can train the chatbot for that.

**Comment by Mayank77maruti** [comment]
Don't forget to star the repo. 
Thank you for contributing.

**Comment by Monika-1082005** [comment]
@Mayank77maruti Ok so the available locations that we're going to provide can be any random location(from any website) or you have some kind of data as per which the chatbot has to provide the details to the user?

**Comment by Mayank77maruti** [comment]
Hacktoberfest is about to wrap up , speed up the work buddy.
All the best.
