### ISSUE TITLE
Bug : Navbar "Images" Icon Not Scrolling  to  Image Section 

### ISSUE THREAD

**Issue by RayyanSeliya** [Mayank77maruti/603WorkVed#30]
---

**To Reproduce**  
1. Go to the website.
2. Click on the "Images" icon in the navbar.
3. Observe that nothing happens, and it doesn't redirect to the intended "Images" page.

**Expected behavior**  
Clicking on the "Images" icon should redirect me to the "Images" page. I have provided a screenshot of the page where I expect to land.

**Screenshots**  

![Screenshot 2024-10-08 005859](https://github.com/user-attachments/assets/1f5aad91-2eea-4634-a5fb-604291cdbee4)

**Desktop**  
- OS: Windows
- Browser: Microsoft edge 
- Version:  129.0.2792.79

**Additional context**  
The "Images" icon in the navbar is currently not functioning as expected and is not redirecting me to the "Images" page.

**Request**
Kindly add the Hacktoberfest tag to this issue, as I would like to work on resolving it as part of the event.

---

**Comment by RayyanSeliya** [comment]
please assign me this issue

**Comment by Mayank77maruti** [comment]
Hey @RayyanSeliya , welcome to our repo, Donot Forget to give a star ⭐.
