### ISSUE TITLE
Improvement in Footer

### ISSUE THREAD

**Issue by Deekshashakyawal** [Mayank77maruti/603WorkVed#32]
I would like to adjust the golden pattern background and the information box such that it looks more readable and enhance the overall appearance of this block. Please Assign me this , Also I want to let you know that my previous merged pull requests are now being marked on my hacktoberfest profile progress. Thank you for the opportunity.

![Screenshot 2024-10-09 164624](https://github.com/user-attachments/assets/45d72d5b-f621-4351-a78c-1c44fa82812c)

**Comment by Mayank77maruti** [comment]
ok works.
