### ISSUE TITLE
Enhance Links Visibility

### ISSUE THREAD

**Issue by Deekshashakyawal** [Mayank77maruti/603WorkVed#4]
The links on the left and right are not visible enough.
I would like to change the color of link text or try something else on it.

![Screenshot 2024-10-01 160504](https://github.com/user-attachments/assets/99fd5d74-27af-4a52-9be1-dbef41375848)

Also I need help in setting up environment for this project , as I'm facing some difficulties to run the project, If possible please provide steps or guidelines to setup and run .

**Comment by Mayank77maruti** [comment]
on vs code , open the index.html file and right click on open from live server, the project will start. Live server is an extension on vs code you can easily download it from extensions part of vs code.

**Comment by Deekshashakyawal** [comment]
Thank you , It worked !

**Comment by Deekshashakyawal** [comment]
Does this looks alright ?

![Screenshot 2024-10-01 171540](https://github.com/user-attachments/assets/2688fb16-ee9b-4a68-a4c0-29b4e41e6f19)


![Screenshot 2024-10-01 172124](https://github.com/user-attachments/assets/46dba33f-0dac-402d-ba23-76ce5c5a7fae)

**Comment by Mayank77maruti** [comment]
#5 is merged.
