### ISSUE TITLE
Make the testmonial section visibility better

### ISSUE THREAD

**Issue by Mayank77maruti** [Mayank77maruti/603WorkVed#8]
**Describe the bug**
in the testimonial section the text is not completely visible.

**To Reproduce**

**Video Explanation**
A clear video showing the bug.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by prayag78** [comment]
Hello @Mayank77maruti 
I would like to complete this task.

**Comment by Mayank77maruti** [comment]
@prayag78 , Don't forget to star the repo.
you can start contributing.
