### ISSUE TITLE
Image Loading is slow use cdn like sirv to fetch image

### ISSUE THREAD

**Issue by Mayank77maruti** [Mayank77maruti/603WorkVed#9]
**Is your feature request related to a problem? Please describe.**
Image Loading is slow use cdn like sirv to fetch image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrhat05** [comment]
@Mayank77maruti I'm ready to work on this

**Comment by Mayank77maruti** [comment]
first complete the assigned issue , then i would assign this.

**Comment by Mayank77maruti** [comment]
Hey @mrhat05 , you start working on this.
